### ISSUE TITLE
Which command is actually setting the new mac?

### ISSUE THREAD

**Issue by codecowboy** [shilch/macchanger#1]
I've been through the source and it seems to be `networksetup -detectnewhardware`. Is that the underlying macos command being run?

**Comment by codecowboy** [comment]
Sorry, I realised it's` ifconfig $1 ether $2 2> /dev/null`

**Comment by shilch** [comment]
Hi,

yes, ifconfig sets the new mac address on the selected interface. The `networksetup -detectnewhardware` is required for wifi in order for the new mac to get detected by the driver IIRC. Don't quote me on that, the last commit was 4 years ago. 😅
